env: prod
auth:
  local:
    mysql-host: 127.0.0.1
    mysql-user: root
    mysql-pass: 12345678
    mysql-db: books_scraper
  prod:
    mysql-host: 127.0.0.1
    mysql-user: root
    mysql-pass: 12345678
    mysql-db: books_scraper
