env: local
auth:
  local:
    mysql-host: mysql_db
    mysql-port: 3306
    mysql-user: root
    mysql-pass: BjksXqdHWKGKuMA9
    mysql-db: books_scraper
  prod:
    mysql-host:
    mysql-port:
    mysql-user:
    mysql-pass:
    mysql-db:
